apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw
  namespace: hw
spec:
  selector:
    matchLabels:
      app: hw
  template:
    metadata:
      labels:
        app: hw
    spec:
      containers:
        - name: hw
          image: docker.io/siddharth67/hw:1.0.1 # {"$imagepolicy": "flux-system:docker-policy"}
          imagePullPolicy: IfNotPresent
