apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: docker-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: docker-repo
  policy:
    semver:
      range: 1.0.x
