apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kust-helm-shapes
  namespace: flux-system
spec:
  interval: 10s
  path: ./helm-chart
  prune: true
  sourceRef:
    kind: GitRepository
    name: source-helm-shapes
  targetNamespace: shapes
