apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: gh-oci
  namespace: flux-system
spec:
  interval: 10s
  provider: generic
  ref:
    tag: 1.0.0
  secretRef:
    name: ghcr-secret
  url: oci://ghcr.io/sidd-harth/hw
